### ISSUE TITLE
Improve handling of metadata

### ISSUE THREAD

**Issue by sergeevabc** [Destitute-Streetdwelling-Guttersnipe/patcher-in-browser#1]
Search-and-replace of byte sequences works well, congratulations.
But there is an issue with displaying some patch names and comments.
In particular, I expect to see the following 

![2024-0128-2155 browser patcher 01](https://github.com/Destitute-Streetdwelling-Guttersnipe/patcher-in-browser/assets/373718/35b389c7-8440-4f5e-85c3-b0976844ab56)

But your script struggles to convert some slashes and some dots into URL.
Perhaps it is the limitation of `urlencode` and we should use `base64`?

**Comment by Destitute-Streetdwelling-Guttersnipe** [comment]
I convert spaces to dashes and join lines with dots before putting patches into URL.
And I reverse them back when loading from URL.
This conversion was only intended for patches, not for all kind of text in comment.

Now that I added support for comments, I will stop using dashes and dots in this conversion, so that they can be used in comments.
I will find a rarely used ASCII character and convert spaces into that one, and I will keep lines as JSON array instead of joining them (before putting patches into URL).

**Comment by sergeevabc** [comment]
Looking forward to trying it out.

**Comment by sergeevabc** [comment]
Still not possible to use \ in the patch name as is, e.g. AppName x86\x64. I mean, it's not intuitive that I should put `\\` there. If everything that is typed in the patch field is automatically converted, then the one who makes the patch has to encode the patch name himself. Perhaps you could make that field editable, e.g. by double-click. 

In fact, I believe two separate fields is better than mixing them: one for bytes only, one for comments (patch name, program version, instructions, etc).

**Comment by sergeevabc** [comment]
Another issue is related to textarea width. If a comment or a sequence of bytes is long enough, then the line is wrapped, which gives the impression that it lacks some # or the replacing part is missing.

![2024-0130-1000 browser patcher 02](https://github.com/Destitute-Streetdwelling-Guttersnipe/patcher-in-browser/assets/373718/55283bd4-ee7a-422e-acd0-f2c535e9cdc3)

Solution is to use `<textarea wrap="off">`.

**Comment by Destitute-Streetdwelling-Guttersnipe** [comment]
> Still not possible to use \ in the patch name as is, e.g. AppName x86\x64. I mean, it's not intuitive that I should put `\\` there. If everything that is typed in the patch field is automatically converted, then the one who makes the patch has to encode the patch name himself. Perhaps you could make that field editable, e.g. by double-click.
> 
> In fact, I believe two separate fields is better than mixing them: one for bytes only, one for comments (patch name, program version, instructions, etc).

I updated it to allow editing of patch name. The default name is Patchy McPatchface.

About the comment, that's a feature to switch on/off some patches for testing different patching ideas.
You can also put more metadata into comments (such as target name, version, guides ...)

**Comment by sergeevabc** [comment]
We're definitely moving in the right direction. I see no complaints from end users about 'apply patch' mode, i.e. 'select the required file and press the button'. But the creation part is still confusing: I can't generate the link or update the link without applying the patch to any dummy file, nor there is a way to reset the form. You see, my ideas of expected convenience are shaped by the tool [CyberChef](https://gchq.github.io/CyberChef/).

**Comment by Destitute-Streetdwelling-Guttersnipe** [comment]
@sergeevabc I added a feature to update patches to URL when the patches input lose focus.

I like CyberChef and I used it for patching before creating this patcher. However, I want to keep this tool simple and focused.

**Comment by sergeevabc** [comment]
Hmm. I struggle to grasp how to use comparison feature. In programs like diff, winmerge, beyondcompare, that thing is clear: they ask me to specify the original file and the modified file, then they show the difference. And here it is suggested to specify one file (the label says 'File to be compared'). I tried, but with no luck.

**Comment by Destitute-Streetdwelling-Guttersnipe** [comment]
It compare 2 files: "File to be patched" and "File to be compared".
Yes, the UI is not really intuitive. I may add some CSS styling as a hint to this behavior.

**Comment by sergeevabc** [comment]
Labels play the vital part, indeed, should be as clear as possible.

For example:
File to be patched -> Original file to be patched
Compare file (Diff hex bytes) -> Compare original and modified files (optional) 
File to be compared -> Modified file to be compared

A few issues with that. There is no button to start the comparison, there is no way to track the progress. It starts automatically when both files are chosen and I observe nothing for a long time, for example, when comparing 150MB files.

**Comment by Destitute-Streetdwelling-Guttersnipe** [comment]
I improved the labels for file inputs. And I added the progress bar for loading of files.

There's still no progress bar for comparing/patching. I think this requires web worker or requestAnimationFrame.
